# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/DS',
                'doc_host': 'https://pralinor.github.io',
                'git_url': 'https://github.com/pralinor/DS',
                'lib_path': 'DS'},
  'syms': {'DS.core': {'DS.core.foo': ('core.html#foo', 'DS/core.py')}}}
